import psycopg2

# Connect to PostgreSQL
conn = psycopg2.connect(
    database="CSE682",
    user="postgres",
    password="postgres",
    host="localhost",
    port="5432"
)

# Create a cursor object
cursor = conn.cursor()

# Function to insert an image into the test_product table
def insert_image(product_id, product_type, product_name, product_desc, product_keywords, image_path, product_price):
    # Read the image file in binary mode
    with open(image_path, 'rb') as file:
        image_data = file.read()

    # Insert the image into the table
    cursor.execute(
        "INSERT INTO ONLINE_RETAIL.product_info (product_id, product_type, product_name, product_desc, product_keywords, product_image, product_price) VALUES (%s, %s, %s, %s, %s, %s, %s)",
        (product_id, product_type, product_name, product_desc,product_keywords, image_data, product_price)
    )

# Insert the  images into the table

insert_image(1001, 'Furniture', 'Modern Upholstered Armchair (Side View)', 'Enhance your living space with this sleek, modern upholstered armchair. Featuring a minimalist design with clean lines and a sturdy wooden frame, this chair combines comfort and style. Its soft fabric upholstery in a dark gray tone ensures durability and elegance, making it perfect for contemporary or classic interiors. Ideal for living rooms, reading nooks, or offices.', 'armchair, modern chair, upholstered chair, dark gray armchair, wooden legs chair', '/Users/tarini/Desktop/proj_cse682/test_images/selected_images/50a9a8e3.jpg', 300)
insert_image(1002, 'Furniture', 'Recliner Armchair', 'Relax in style with this comfortable recliner armchair. Designed with plush cushions and soft fabric upholstery in a neutral gray shade, this chair offers both support and luxury. The recliner mechanism allows you to adjust the backrest and footrest for ultimate relaxation. Perfect for living rooms, TV lounges, or reading corners.', 'recliner chair, gray armchair, fabric recliner, living room furniture, comfortable chair.', '/Users/tarini/Desktop/proj_cse682/test_images/selected_images/50a99ded.jpg', 350)
insert_image(1003, 'Furniture', 'Tufted Faux Leather Bench', 'Add a touch of sophistication to your home with this tufted faux leather bench. Featuring a padded seat with button-tufted detailing and a rich brown finish on the sturdy wooden legs, this bench is both stylish and functional. Ideal for entryways, bedrooms, or as additional seating in living spaces.', 'faux leather bench, tufted bench, brown bench, entryway furniture, padded seating.', '/Users/tarini/Desktop/proj_cse682/test_images/selected_images/50a479e6.jpg', 250)
insert_image(1004, 'Shoes', 'Kids Slip-On Sneakers', 'Keep your little ones active and stylish with these lightweight slip-on sneakers. Designed with breathable mesh uppers and a flexible sole for all-day comfort, these sneakers feature a fun red-and-blue color combination. The easy slip-on design ensures convenience for kids on the go. Perfect for casual outings or playtime.', ' kids sneakers, slip-on shoes, breathable sneakers, lightweight shoes for kids, red-and-blue sneakers.', '/Users/tarini/Desktop/proj_cse682/test_images/selected_images/50a58c64.jpg', 100)
insert_image(1005, 'Furniture', 'Nature-Inspired Wall Decal Set', 'Transform your living or workspace with this nature-inspired wall decal set. Featuring a whimsical design of tree branches, birdhouses, and birds in a black and green color scheme, this peel-and-stick decal adds a refreshing and creative touch to any room. Easy to apply and remove without damaging walls, its perfect for offices, bedrooms, or kids rooms. Includes the quote: Its a world inspired by nature.', 'wall decals, nature wall stickers, peel-and-stick decals, tree branch decor, birdhouse wall art', '/Users/tarini/Desktop/proj_cse682/test_images/selected_images/50a06113.jpg', 200)
insert_image(1006, 'Furniture', 'Mid-Century Modern Wooden Dining Table', 'Bring timeless elegance to your dining space with this mid-century modern wooden dining table. Crafted from high-quality solid wood with a warm walnut finish, this table features clean lines and tapered legs for a minimalist aesthetic. Its compact size makes it ideal for small dining areas or apartments while still providing ample space for meals and gatherings.', 'wooden dining table, mid-century modern table, walnut finish table, compact dining furniture, solid wood table', '/Users/tarini/Desktop/proj_cse682/test_images/selected_images/50a6947c.jpg', 250)
insert_image(1007, 'Shoes', 'Mens Classic Leather Oxford Shoes', 'Elevate your formal attire with these mens classic leather oxford shoes. Crafted from premium black leather with a polished finish, these shoes feature a timeless lace-up design and a comfortable cushioned insole. Perfect for business meetings, formal events, or elegant everyday wear.', ' mens oxford shoes, black leather shoes, formal footwear, classic dress shoes, lace-up shoes', '/Users/tarini/Desktop/proj_cse682/test_images/selected_images/50a7081b.jpg', 150)
insert_image(1008, 'Shoes', ' White Sneakers with Red Accent', 'Step out in style with these classic white sneakers featuring bold red accents. Made from durable synthetic leather with perforated detailing for breathability, these sneakers offer both fashion and comfort. The cushioned insole and sturdy rubber sole make them perfect for casual outings or everyday wear. A versatile addition to your wardrobe.', 'white sneakers, red-accent shoes, casual footwear, synthetic leather sneakers, unisex sneakers', '/Users/tarini/Desktop/proj_cse682/test_images/selected_images/50a7716f.jpg', 200)
insert_image(1009, 'Furniture', 'Black Microfiber Bed Sheet Set', 'Experience ultimate comfort with this black microfiber bed sheet set. Made from ultra-soft and breathable microfiber fabric, these sheets are wrinkle-resistant and durable for long-lasting use. Perfect for any bedroom decor, this set includes a fitted sheet, flat sheet, and pillowcases to complete your bedding ensemble.', 'black bed sheets, microfiber sheet set, wrinkle-resistant bedding, soft bed linen, queen-size sheets', '/Users/tarini/Desktop/proj_cse682/test_images/selected_images/50a53098.jpg', 75)
insert_image(1010, 'Furniture', 'Upholstered Swivel Bar Stool', 'Upgrade your dining or bar area with this upholstered swivel bar stool. Designed with a plush tan fabric seat and backrest for maximum comfort, this stool features a sturdy wooden frame with a rich walnut finish. The 360-degree swivel functionality adds convenience, making it ideal for kitchen counters or home bars.', 'swivel bar stool, upholstered bar chair, tan bar stool, wooden frame stool, counter-height seating', '/Users/tarini/Desktop/proj_cse682/test_images/selected_images/50a75239.jpg', 150)
insert_image(1011, 'Shoes', 'Womens Satin Purple High Heels', 'Make a bold statement with these womens satin purple high heels. Featuring a luxurious satin finish and a classic pointed-toe design, these heels are perfect for formal occasions, weddings, or evening events. The 4-inch stiletto heel adds elegance and height while ensuring a confident stride.', 'purple high heels, satin heels, womens formal shoes, stiletto heels, evening footwear', '/Users/tarini/Desktop/proj_cse682/test_images/selected_images/50ab7da7.jpg', 150)
insert_image(1012, 'Shoes', 'Mens Textured Black Sneakers', 'Step into comfort and style with these mens textured black sneakers. Featuring a sleek design with a breathable textured upper and a durable white rubber sole, these sneakers are perfect for casual outings or everyday wear. The lace-up closure ensures a secure fit, while the lightweight construction adds to all-day comfort.', 'mens black sneakers, casual shoes, textured sneakers, lace-up footwear, comfortable sneakers', '/Users/tarini/Desktop/proj_cse682/test_images/selected_images/50ab292c.jpg', 125)
insert_image(1013, 'Shoes', 'Womens Slip-On Walking Shoes', 'Stay active and comfortable with these womens slip-on walking shoes. Featuring a breathable black mesh upper with a stylish pattern and a lightweight white sole, these shoes are perfect for casual outings, walking, or light workouts. The slip-on design ensures easy wear, while the cushioned insole provides all-day comfort.', 'womens walking shoes, slip-on sneakers, breathable shoes, lightweight footwear, black mesh shoes', '/Users/tarini/Desktop/proj_cse682/test_images/selected_images/50abf019.jpg', 150)
insert_image(1014, 'Furniture', 'Modern Wall-Mounted Bookshelf', 'Organize your space with this modern wall-mounted bookshelf featuring a unique geometric design. Made from sturdy engineered wood in a neutral beige finish, this shelf offers multiple compartments to display books, decor items, or plants. Its sleek and compact design makes it ideal for living rooms, offices, or bedrooms.', 'wall-mounted bookshelf, geometric shelf design, modern storage solution, beige bookshelf, decorative shelving unit', '/Users/tarini/Desktop/proj_cse682/test_images/selected_images/50aec0ed.jpg', 125)
insert_image(1015, 'Shoes', 'Kids Space-Themed Sneakers', 'Let your little ones explore the universe with these kids space-themed sneakers. Designed in a soft blue color with fun gold illustrations of astronauts, stars, and rockets, these lace-up sneakers are both stylish and durable. The white rubber sole ensures comfort and grip, making them perfect for playtime or casual wear.', 'kids sneakers, space-themed shoes, blue sneakers for kids, lace-up footwear, astronaut design shoes', '/Users/tarini/Desktop/proj_cse682/test_images/selected_images/50b1e30b.jpg', 125)
insert_image(1016, 'Furniture', 'Upholstered Platform Bed with Tufted Headboard', 'Create a cozy and elegant bedroom retreat with this upholstered platform bed featuring a tufted headboard. The soft beige fabric complements any decor style, while the sturdy wooden frame ensures durability. Pair it with your favorite bedding to complete the look. Perfect for master bedrooms or guest rooms.', 'upholstered bed frame, tufted headboard bed, beige platform bed, modern bedroom furniture, queen-size bed frame', '/Users/tarini/Desktop/proj_cse682/test_images/selected_images/50b2cde0.jpg', 250)
insert_image(1017, 'Shoes', 'Mens Classic Blue Canvas Sneakers', 'Add a pop of color to your casual wardrobe with these mens classic blue canvas sneakers. Featuring a vibrant blue upper, durable white rubber toe cap, and lace-up closure, these sneakers are designed for both style and comfort. The soft inner lining with patterned detailing adds a unique touch, making them perfect for everyday wear or casual outings.', ' mens blue sneakers, canvas shoes, lace-up sneakers, casual footwear, white rubber toe cap', '/Users/tarini/Desktop/proj_cse682/test_images/selected_images/50b63d42.jpg', 150)
insert_image(1018, 'Bag', 'Large Maroon Backpack with Multiple Compartments', 'Stay organized on the go with this large maroon backpack. Designed with multiple zippered compartments and side pockets, this backpack offers ample storage for books, laptops, or travel essentials. The padded shoulder straps ensure comfortable carrying, while the durable fabric construction makes it perfect for school, work, or travel.', 'maroon backpack, large travel bag, multi-compartment backpack, laptop bag, school bag', '/Users/tarini/Desktop/proj_cse682/test_images/selected_images/50b82ba3.jpg', 250)
insert_image(1019, 'Shoes', 'Mens Tan Low-Top Sneakers', 'Step into effortless style with these mens tan low-top sneakers. Crafted with a sleek tan canvas upper and a contrasting white rubber sole, these sneakers are perfect for casual outings or everyday wear. The minimalistic design pairs well with jeans or chinos for a laid-back yet polished look.', 'mens tan sneakers, low-top shoes, casual canvas footwear, minimalist sneakers, white sole shoes', '/Users/tarini/Desktop/proj_cse682/test_images/selected_images/50b83c0b.jpg', 150)
insert_image(1020, 'Furniture', 'Green Upholstered Storage Ottoman Bench', 'Add functionality and style to your space with this green upholstered storage ottoman bench. Featuring a spacious interior for storing blankets, toys, or other essentials, this bench is both practical and elegant. The soft fabric upholstery and sturdy wooden legs make it a versatile addition to living rooms, bedrooms, or entryways.', 'green ottoman bench, storage furniture, upholstered bench, living room decor, multifunctional seating', '/Users/tarini/Desktop/proj_cse682/test_images/selected_images/50b0143e.jpg', 200)




# Commit the transaction and close the connection
conn.commit()
cursor.close()
conn.close()
